import Container from '@/components/shared/container'
import HomeNavbar from '@/components/shared/layout/HomeNavbar'
import RightSideBar from '@/components/shared/layout/RightSideBar'
import { Sidebar } from '@/components/shared/layout/Sidebar'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Toaster } from 'react-hot-toast'
import './globals.css'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<div className='flex h-screen'>
					<Toaster reverseOrder={false} />
					<Sidebar />
					<div className='flex flex-col'>
						<HomeNavbar />
						<div className='flex justify-between'>
							<Container>{children}</Container>
							<RightSideBar />
						</div>
					</div>
				</div>
			</body>
		</html>
	)
}
